name: hacksilver_ledger
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  file_picker: ^10.3.10
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_iconpicker: ^4.0.3
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^8.0.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
